import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="min-h-screen">
        <Header />

        <main className="pt-36 pb-24 w-full px-6 min-h-screen">
          <div className="w-full h-full mx-auto max-w-[81rem]">{children}</div>
        </main>
      </body>
    </html>
  )
}
